import Link from "next/link";
import { ArrowLeft, BadgeCheck, Download, ShieldCheck, Sparkles } from "lucide-react";
import { getCategories, getHomeCollections } from "@/services/catalog";
import { ProductCard } from "@/components/product-card";
import { Button } from "@/components/ui/button";

export default async function Home() {
  const [collections, categories] = await Promise.all([getHomeCollections(), getCategories()]);
  const featured = collections.featured.products;
  const featuredSubscriptions = featured.filter((product) => product.subscription_type !== "none");
  return <main>
    <section className="relative overflow-hidden bg-zinc-950 text-white"><div className="absolute -left-24 -top-32 size-96 rounded-full border-[60px] border-amber-400/20" /><div className="container-shell grid min-h-[560px] items-center gap-12 py-20 lg:grid-cols-[1.1fr_.9fr]"><div className="relative"><p className="eyebrow text-amber-400">سوقك الرقمي العربي</p><h1 className="mt-5 display-title max-w-3xl">أفكار جاهزة.<br /><span className="text-amber-400">إنجاز أسرع.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-zinc-400">اكتشف كتباً وقوالب وملفات رقمية منتقاة بعناية لتبدأ مشروعك وتتعلم مهارة جديدة اليوم.</p><div className="mt-9 flex flex-wrap gap-3"><Button size="lg" className="bg-amber-400 text-black hover:bg-amber-500" render={<Link href="/shop" />}>استكشف المتجر <ArrowLeft /></Button><Button size="lg" variant="outline" className="border-zinc-700 bg-transparent text-white hover:bg-zinc-800" render={<Link href="/categories" />}>تصفح التصنيفات</Button></div></div><div className="relative grid grid-cols-2 gap-4"><div className="mt-12 rounded-[2rem] bg-zinc-900 p-7"><Sparkles className="size-9 text-amber-400" /><p className="mt-16 text-2xl font-black">منتجات<br />تُلهمك</p></div><div className="rounded-[2rem] bg-amber-400 p-7 text-black"><Download className="size-9" /><p className="mt-16 text-2xl font-black">تحميل<br />فوري وآمن</p></div></div></div></section>
    <section className="container-shell section-space"><div className="grid gap-4 sm:grid-cols-3"><div className="flex gap-4 rounded-2xl border bg-card p-5"><ShieldCheck className="size-7 text-primary" /><div><h2 className="font-bold">شراء آمن</h2><p className="mt-1 text-sm text-muted-foreground">بوابات موثوقة وبيانات محمية</p></div></div><div className="flex gap-4 rounded-2xl border bg-card p-5"><Download className="size-7 text-primary" /><div><h2 className="font-bold">وصول فوري</h2><p className="mt-1 text-sm text-muted-foreground">حمّل منتجاتك بعد تأكيد الدفع</p></div></div><div className="flex gap-4 rounded-2xl border bg-card p-5"><BadgeCheck className="size-7 text-primary" /><div><h2 className="font-bold">اختيار موثوق</h2><p className="mt-1 text-sm text-muted-foreground">محتوى رقمي بجودة عالية</p></div></div></div></section>
    <section className="container-shell pb-20"><div className="mb-8 flex items-end justify-between"><div><p className="eyebrow">اشتراكات Izée live</p><h2 className="mt-2 text-3xl font-black">Netflix، Shahid VIP وChatGPT+</h2></div><Link href="/shop" className="flex items-center gap-2 text-sm font-bold text-primary">عرض الكل <ArrowLeft className="size-4" /></Link></div>{featuredSubscriptions.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{featuredSubscriptions.slice(0, 4).map((product) => <ProductCard key={product.id} product={product} />)}</div> : <div className="rounded-2xl border border-dashed p-12 text-center text-muted-foreground">ستظهر الاشتراكات المختارة هنا بعد تطبيق بيانات المتجر.</div>}</section>
    <section className="container-shell pb-20"><div className="mb-8 flex items-end justify-between"><div><p className="eyebrow">مختارات رقمية</p><h2 className="mt-2 text-3xl font-black">منتجات تستحق وقتك</h2></div><Link href="/shop" className="flex items-center gap-2 text-sm font-bold text-primary">عرض الكل <ArrowLeft className="size-4" /></Link></div>{featured.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{featured.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <div className="rounded-2xl border border-dashed p-12 text-center text-muted-foreground">ستظهر المنتجات المختارة هنا قريباً.</div>}</section>
    <section className="bg-zinc-900 py-20"><div className="container-shell"><div className="mb-8"><p className="eyebrow">استكشف</p><h2 className="mt-2 text-3xl font-black">حسب اهتمامك</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.slice(0, 8).map((category) => <Link key={category.id} href={`/categories/${category.slug}`} className="group rounded-xl border border-zinc-800 bg-zinc-950 p-6 transition hover:border-amber-400 hover:bg-zinc-800"><span className="text-3xl text-amber-400">◈</span><h3 className="mt-8 font-bold">{category.name}</h3><p className="mt-2 text-sm text-zinc-400 group-hover:text-zinc-200">اكتشف المجموعة</p></Link>)}</div></div></section>
  </main>;
}
