import Link from "next/link";
import { getProfile } from "@/lib/auth";
import { getMyFavorites, getMyReviews } from "@/services/account";
import { signOutAction } from "@/services/auth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { updateProfileAction } from "@/services/account";
const titles: Record<string, string> = { profile: "الملف الشخصي", favorites: "المفضلة", reviews: "تقييماتي", settings: "الإعدادات" };
export default async function AccountSection({ params }: { params: Promise<{ section: string }> }) { const { section } = await params; const profile = await getProfile(); if (section === "profile") return <main className="container-shell section-space"><h1 className="text-4xl font-black">الملف الشخصي</h1><form action={async (formData) => { "use server"; await updateProfileAction(formData); }} className="mt-8 max-w-xl space-y-5 rounded-2xl border bg-card p-6"><div><Label htmlFor="fullName">الاسم</Label><Input id="fullName" name="fullName" defaultValue={profile?.full_name ?? ""} className="mt-2" /></div><div><Label htmlFor="phone">الهاتف</Label><Input id="phone" name="phone" defaultValue={profile?.phone ?? ""} className="mt-2" /></div><Button>حفظ البيانات</Button></form></main>; if (section === "settings") return <main className="container-shell section-space"><h1 className="text-4xl font-black">الإعدادات</h1><form action={async () => { "use server"; await signOutAction(); }} className="mt-8"><Button variant="outline">تسجيل الخروج</Button></form></main>; const data = section === "favorites" ? await getMyFavorites() : await getMyReviews(); return <main className="container-shell section-space"><h1 className="text-4xl font-black">{titles[section] ?? "حسابي"}</h1><div className="mt-8 grid gap-4">{data.map((item) => <div key={item.id} className="rounded-2xl border bg-card p-5">{("product" in item && item.product) ? <Link className="font-bold text-primary" href={`/products/${item.product.slug}`}>{item.product.name}</Link> : <p className="text-muted-foreground">{("comment" in item && item.comment) || "تم حفظ العنصر في حسابك."}</p>}</div>)}{!data.length ? <p className="rounded-2xl border border-dashed p-12 text-center text-muted-foreground">لا توجد عناصر هنا بعد.</p> : null}</div></main>; }
